### ISSUE TITLE
Split `IsahcError::Timeout` into `IsahcError::DnsTimeout`

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#104]
Both DNS resolver timeouts and request timeouts are reported as `IsahcError::Timeout` and I can't differentiate between them.

**Comment by sagebind** [comment]
I don't think we can make that distinction; libcurl just returns `CURLE_OPERATION_TIMEDOUT` without any specific error string for both cases. I think a new error code would have to be added to libcurl to make this possible.

**Comment by kathampy** [comment]
Command line `curl` prints a different error when using `--dns-servers` with `c-ares`.
