### ISSUE TITLE
Patch bundled libcurl when upstream CVEs come out

### ISSUE THREAD

**Issue by DemiMarie** [sagebind/isahc#171]
Many of them may not effect us (TFTP, FTP, etc), but we should still patch them.

**Comment by sagebind** [comment]
Any particular examples you are referring to?

This is probably an issue for the curl-sys crate to handle, as long as we keep up to date with the latest upstream versions. To my knowledge, curl-sys keeps relatively up-to-date with upstream source.

**Comment by DemiMarie** [comment]
None in particular; cURL’s HTTP implementation has a fantastic security record.

**Comment by sagebind** [comment]
Closing, as I think the question here is resolved. The curl and curl-sys crate have a pretty good record of staying up-to-date with upstream libcurl patches. Feel free to re-open if there's more work to be done.
