### ISSUE TITLE
Disable extensive logging

### ISSUE THREAD

**Issue by ayrat555** [sagebind/isahc#192]
Hello!

I just updated `isahc` to `0.9.3`. It started spamming log messages:

```
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -> shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] <- shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -- shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] send_async; method=GET uri=https://financefeeds.com/feed/
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -> send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] <- send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -> shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] <- shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -- shared
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] send_async; method=GET uri=http://www.express.pk/feed/
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -> send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] <- send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -> send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] <- send_async
May 31 09:18:20 vps695005 bash[32530]: [2020-05-31T07:18:20Z INFO  isahc::client] -- send_async
```

I use `isahc` to fetch feeds for  https://github.com/ayrat555/el_monitorro .
I start the binary with `RUST_LOG=info RUST_BACKTRACE=1 cargo ...`. 

Can `isahc` only print error level logs?

**Comment by sagebind** [comment]
These are coming from the recently released integration with [tracing](https://github.com/tokio-rs/tracing) (#77). The logs you are seeing are emitted under the `tracing::span` log target, which is included in the `RUST_LOG` filter of `info`, and are meant to be able to trace individual operations that are being performed. Seeing just Isahc logs would be something like `RUST_LOG=isahc=info`.

That said, I can see how these logs are annoying at the general `info` level and its not exactly my favorite either. I will see about changing these to be at the `trace` log level instead.

**Comment by ayrat555** [comment]
Can I completely disable `isahc` log? I already log the information I need from `isahc`

**Comment by sagebind** [comment]
Perhaps a filter like this would work: `RUST_LOG=info,isahc=error`. I think that would log everything that is `INFO` or above, except for Isahc, where only `ERROR` logs will be written. I'm assuming your using [env_logger](https://crates.io/crates/env_logger)?
