### ISSUE TITLE
Use MesaLink as an SSL/TLS engine

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#22]
By their own words, [MesaLink](https://github.com/mesalock-linux/mesalink) is, "A memory-safe and OpenSSL-compatible TLS library". It is written primarily in Rust and uses [Ring](https://github.com/briansmith/ring) and [Rustls](https://github.com/ctz/rustls) under the hood.

The ideal scenario for Isahc would be to use MesaLink unconditionally on all platforms, which provides consistency and stability across systems. It also would allow us to add more specific TLS customization options like the ones described in #89.

**Blockers**

- [x] https://github.com/alexcrichton/curl-rust/pull/280
- [x] curl-sys and MesaLink do not build on Windows
- [ ] https://github.com/mesalock-linux/mesalink/issues/36

**Comment by sagebind** [comment]
Upstream pull request: https://github.com/alexcrichton/curl-rust/pull/280

**Comment by kathampy** [comment]
If I add `curl = { version = "0.4.24", features = ["mesalink"] }` to my project, would MesaLink be used by Isahc, or would I need to patch Isahc?

**Comment by sagebind** [comment]
I believe MesaLink would be used by Isahc, since Cargo should see them as compatible and select just one curl version with the sum of all features requested by all crates. I'd try it and see, that might be a good way to experiment before Isahc gains official support.

Printing the result of `isahc::version()` should tell you which SSL engine is being used.

**Comment by kathampy** [comment]
HTTP/2 TLS doesn't work with MesaLink on macOS.

**Comment by sagebind** [comment]
Hmm, that's unfortunate. That is a pretty significant blocker to making it any sort of default feature.

**Comment by kathampy** [comment]
I don't see `mesalink` calling `rustls`' ALPN functions anywhere.

**Comment by Arzte** [comment]
MesaLink now builds on windows as of version 1.0 https://github.com/mesalock-linux/mesalink/releases/tag/v1.0.0

**Comment by gavrie** [comment]
@sagebind I'm a bit worried by "use MesaLink unconditionally on all platforms". Would that mean that OpenSSL support will be deprecated? 

Many people prefer to rely on a native, OS-provided TLS implementation that is maintained and includes security fixes as they are released by vendors. The great advantage of using having `ishac` use OpenSSL is that applications built with it can make use of these fixes automatically once the underlying shared library is updated.

Using `rustls` (or any other custom TLS implementation) would mean missing out on those fixes.

**Comment by sagebind** [comment]
This is the age-old debate between rustls and shared libraries/APIs provided by the system, which I suppose I don't want to touch that debate with a 10-foot pole. Both sides arguably have their benefits and drawbacks, and the supporters of each side can be pretty vocal. So I suppose Isahc will have to always offer the choice of TLS implementations.

This just means that I don't think we can _ever_ provide one API for doing things such as using in-memory certs, because the underlying TLS APIs are all wildly different and we might not even know which one we are using until runtime.

Regardless, it seems like MesaLink is dead now, so we can probably close this issue anyway.
