### ISSUE TITLE
Implement Clone for HttpClient

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#241]
Since `HttpClient` already does not require mutable access in any of its methods to allow concurrent calls, it would improve ergonomics when sharing a `HttpClient` instance if it implemented `Clone` directly, instead of needing to wrap it in an `Arc` manually.

### Implementation notes

We already use an `Arc` in the client internally to manage the agent's lifetime and to allow it to live beyond the lifetime of the client if the client is dropped while existing requests are still in flight. We could get rid of this `Arc` and instead make the whole client wrapped in an `Arc` and thus accomplish the same thing by having requests hold a clone of the client. That way, we don't need to have more `Arc`s than we already do.

**Comment by braunse** [comment]
I started working on this in #244

**Comment by sagebind** [comment]
This is now available in the [0.9.11 release](https://github.com/sagebind/isahc/releases/tag/0.9.11)!
