### ISSUE TITLE
default user-agent header is malformed

### ISSUE THREAD

**Issue by volfco** [sagebind/isahc#286]
This drove me insane to figure out. This library is sending out a malformed `user-agent` header. 

This library sends `user-agent:curl/7.74.0 isahc/1.0.1` compared to stock cURL: `User-Agent: curl/7.74.0`. 

There is a space omitted after the colon. While this doesn't seem to be invalid HTTP 1/1, It will trip up crappy http parsers who assume `: ` for header fields.

Thanks for building one of the only Rust HTTP libraries that supports Unix sockets!

**Comment by sagebind** [comment]
Thanks for reporting this; sorry this caused so much trouble for you!

This looks to be how Isahc sends all custom header fields with HTTP/1.x (without whitespace), not just the user agent. This is compliant with [RFC 7230, section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2). However, this is a bit unusual and it would probably be better for us to include a single space after the `:` to avoid confusing bad HTTP parsers. I will submit a PR to change this and release a patch version shortly.

**Comment by sagebind** [comment]
This is now fixed in the [1.0.2 release](https://github.com/sagebind/isahc/releases/tag/1.0.2)!

**Comment by volfco** [comment]
Thanks for the quick fix! Awesome work here

**Comment by numerodix** [comment]
I just hit this problem today - 18 months later - when using surf `2.3.2` (latest release) :rofl:

Glad to see my bug report isn't needed. :smile:

**Comment by sagebind** [comment]
Unfortunately Surf uses a very old version of Isahc, so there's not much I can do about that other than advocating that they upgrade to a newer version, which included this, and many other fixes.
