### ISSUE TITLE
How to fetch bytes from GET response

### ISSUE THREAD

**Issue by meghashyam6** [sagebind/isahc#299]
Currently isahc::get() returns Response<Body>. Is there a way I could get the body in bytes(&[u8])? I see macros like text() in prelude but not a byte array

**Comment by sagebind** [comment]
The response [`Body`](https://docs.rs/isahc/1.1.0/isahc/struct.Body.html) implements [`Read`](https://doc.rust-lang.org/stable/std/io/trait.Read.html), so you can simply use the normal methods in the standard library to read the stream into a buffer:

```rust
let mut response = isahc::get("http://example.org")?;
let mut bytes = Vec::new();

// Read the whole response into memory.
response.body_mut().read_to_end(&mut bytes)?;
```
