### ISSUE TITLE
How to copy response to a file

### ISSUE THREAD

**Issue by meghashyam6** [sagebind/isahc#301]
I'm trying to use io::copy to write response into a new file. But Response<Body> doesn't seem to be implementing Read. Is there a workaround?
 let mut out = match File::create(path)?
if io::copy(&mut file, &mut out).is_err() {
    |            ^^^^^^^^ the trait `std::io::Read` is not implemented for `isahc::Response<isahc::Body>`

**Comment by meghashyam6** [comment]
Converted Repsonse<Body> to &[u8]. that worked
```
 let mut bytes = Vec::new();
                        let s = f.body_mut().read_to_end(&mut bytes);
                       return bytes.as_slice()
```

**Comment by sagebind** [comment]
> But Response doesn't seem to be implementing Read

Correct, the whole response doesn't implement `Read`, only the response `Body` implements `Read`, which you can get with `Response::body_mut()`:

```rust
let mut response = isahc::get("https://example.org")?;
let mut file = File::create(path)?;
io::copy(response.body_mut(), &mut file)?;
```

You don't need to read the whole response into memory first. Also, to write to a file, the `prelude` provides the [`copy_to_file`](https://docs.rs/isahc/1.1.0/isahc/trait.ReadResponseExt.html#method.copy_to_file) convenience method for this:

```rust
let mut response = isahc::get("https://example.org")?;
response.copy_to_file(path)?;
```

**Comment by meghashyam6** [comment]
That's awesome!! Somehow I missed that method in prelude. I would never go back to reqwest :)
