### ISSUE TITLE
Sending PATCH request with HttpClient?

### ISSUE THREAD

**Issue by OskarPersson** [sagebind/isahc#327]
How do I send a PATCH request from a `HttpClient`? There doesn't seem to be any `.patch` or `.patch_async` method available?

**Comment by sagebind** [comment]
Thanks for your question! There's no convenience method for `PATCH`, but you can always send a more customized request using [`HttpClient::send`](https://docs.rs/isahc/1.4.0/isahc/struct.HttpClient.html#method.send) or [`HttpClient::send_async`](https://docs.rs/isahc/1.4.0/isahc/struct.HttpClient.html#method.send_async). For example:

```rust
let client = HttpClient::new()?;

let request = Request::patch("https://example.org")
    .header("Content-Type", "application/json")
    .body(r#"{
        "speed": "fast",
        "cool_name": true
    }"#)?;

// Or alternatively
let request = Request::builder()
    .method("PATCH")
    .uri("https://example.org")
    .header("Content-Type", "application/json")
    .body(r#"{
        "speed": "fast",
        "cool_name": true
    }"#)?;

let response = client.send(request)?;
```

**Comment by OskarPersson** [comment]
Ah I see, thank you! :)
