### ISSUE TITLE
isahc didn't use http2 in making request

### ISSUE THREAD

**Issue by haxpor** [sagebind/isahc#384]
I have the following code, please just pay attention on `let request = ....` lines. Code is stripped for brevity.

```rust
    pub fn get_bnb_last_price(&self, ctx: &Context) -> Result<BSCBnbLastPrice, BscError> {
        let raw_url_str = format!("https://api.bscscan.com/api?module=stats&action=bnbprice&apikey={api_key}", api_key=ctx.api_key);
        let url = Url::parse(&raw_url_str).unwrap();

        let request = isahc::Request::get(url.unwrap().as_str())
            .version_negotiation(isahc::config::VersionNegotiation::http2())
            .body(()).unwrap();

        println!("{}", isahc::is_http_version_supported(http::version::Version::HTTP_2));
        println!("{:#?}", request);
        ...
    }
```

`isahc::is_http_version_supported` returns `true` for `HTTP_2`, but debug printing of `request` results in the following

```
Request {
    method: GET,
    uri: https://api.bscscan.com/api?module=stats&action=bnbprice&apikey=<redacted>,
    version: HTTP/1.1,
    headers: {},
    body: (),
}
```

I also printed `Response::headers()` which I got the following

```
{
    "server": "nginx",
    "date": "<redacted> GMT",
    "content-type": "application/json; charset=utf-8",
    "content-length": "215",
    "cache-control": "private",
    "content-encoding": "gzip",
    "vary": "Accept-Encoding",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "Content-Type",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    "x-frame-options": "SAMEORIGIN",
}
```
---
Anyhow, I have `curl` version 7.68.0 installed on my machine in which it is able to communicate with the same URL above in HTTP/2 in which I got the following result via executing command of `curl "<target-url>" -v`

```
*   Trying <redacted>:443...
* TCP_NODELAY set
* Connected to api.bscscan.com (<redacted>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: <redacted>
  CApath: <redacted>
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.bscscan.com
*  start date: <redacted> GMT
*  expire date: <redacted> GMT
*  subjectAltName: host "api.bscscan.com" matched cert's "*.bscscan.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle <redacted>)
> GET /api?module=stats&action=bnbprice&apikey=<redacted> HTTP/2
> Host: api.bscscan.com
> user-agent: curl/7.68.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: <redacted> GMT
< content-type: application/json; charset=utf-8
< content-length: 142
< cache-control: private
< access-control-allow-origin: *
< access-control-allow-headers: Content-Type
< access-control-allow-methods: GET, POST, OPTIONS
< x-frame-options: SAMEORIGIN
< 
* Connection #0 to host api.bscscan.com left intact
```

which confirms the target server supports HTTP/2 communication.

What did I do wrong? How can I make isahc use HTTP/2 for making requests?

**Comment by haxpor** [comment]
**Update**

I can just manually force set `http::version::Version::HTTP_2` like this

```
*request.version_mut() = http::version::Version::HTTP_2;
```

Response returned back successfully. But additional question is how can I know the response is in `h2` procotol?
Because checking via `Response::headers()` doesn't have anything relevant to check for such thing.

Thanks again.

**Comment by sagebind** [comment]
The `Request::version` field is unused by Isahc and is not indicative of what version is being used. It is a field defined by the `http` crate. It wouldn't make sense to check the _request_ version to determine which version is used anyway because the request has not been sent yet and so version negotiation hasn't taken place yet.

`version_negotiation` is the correct method to use to control how Isahc decides which HTTP version to attempt to use. In your first example the server _was_ using HTTP/2, you just were not looking in the right place to find out which version was used.

If you want to know what version was used for a request you need to look at the `Response::version` field as you discovered. This will tell you which version was actually used and which version the server responsed with. HTTP version is never encoded as HTTP headers so you would not expect to find that information there.

**Comment by haxpor** [comment]
Thank you very much @sagebind for taking time to explain internal stuff to me.
All clear, and actually this was not an issue but more about not knowing what's actually happening. Closed now. Thanks.
