### ISSUE TITLE
Incorrect Content-Length in request causes I/O error on Windows

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#57]
Failing test: https://github.com/sagebind/isahc/runs/190511441#step:5:342

When sending a request with a body, if the outgoing `Content-Length` header does not match the size of the actual payload being sent, the request fails with `[56] Failure when receiving data from the peer`.

Note that this might actually be a bug in mockito.

**Comment by mamcx** [comment]
I get this error in osx with this return (using httpie as debug tool):

```
 http -v  --json --session test GET  http://localhost:8080/v1/api/disdarien/orders/pending
GET /v1/api/disdarien/orders/pending HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: application/json
Cookie: auth-cookie=dvKAHae4....
Host: localhost:8080
User-Agent: HTTPie/1.0.3

HTTP/1.1 200 OK
content-encoding: gzip
content-type: application/json
date: Thu, 20 Feb 2020 02:08:58 GMT
transfer-encoding: chunked

{
    "Docs": {
        "docs": []
    }
}
```

**Comment by sagebind** [comment]
@mamcx I'm not sure how this is relevant to this issue? Maybe I'm missing some context. This error is for when you send a request body (like a POST request) and set a `Content-Length` header in the request that doesn't match the length of the actual body.

**Comment by mamcx** [comment]
`Content-Length` is not set here (this come from actix). Is the only response that give me trouble.

**Comment by sagebind** [comment]
You mean Actix not sending a `Content-Length` in the response is causing you trouble when trying to receive it from Isahc? If so, I recommend creating a new issue and providing more details; this one is about Isahc _sending_ a `Content-Length`.

**Comment by sagebind** [comment]
Not able to reproduce any more on the latest version, so this must have gotten fixed at some point along the way.
