### ISSUE TITLE
Dropping an HttpClient aborts all transfers associated with it silently

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#64]
Discovered here: https://github.com/rustasync/surf/issues/36

The title says it all. If you are not careful to keep your `HttpClient` alive long enough to finish all of your outstanding transfers, then your response `Body` will report end-of-stream silently without warning.

This is clearly not good behavior, but it brings up a question: what _is_ good behavior? While `ResponseFuture` explicitly _does_ borrow from `HttpClient`, the returned `Response<Body>` does not, and so it is no longer clear that the response body still depends on the client to do its work.

I see three possible correct behaviors:

1. Add a lifetime to `Body` that matches the lifetime of the associated `HttpClient`. This might be the most "correct" solution, but adding a lifetime to the body will make using it a lot more tedious.
2. When a client is dropped, all associated incomplete streams should return an `io::ErrorKind::BrokenPipe` error.
3. Keep the agent thread alive even if the `HttpClient` is dropped, until all outstanding transfers are either completed or cancelled.

I am currently leaning toward behavior number 3, because it seems like the least surprising one based on the API we present, though the drop behavior of `HttpClient` would no longer be as intuitive. Currently dropping `HttpClient` waits for the agent thread to clean up its resources before returning. Should dropping the last outstanding `Body` also wait until agent resources are cleaned up? Something about asynchronous drops doesn't sit right with me.

**Comment by Byron** [comment]
If going ahead with 3), I wonder if the IO-operation is stopped if the `Response<Body>` is dropped, as would be the case if the `Response<Body>` would keep the `HttpClient` alive.

Being able to just drop anything related to the future and see all corresponding operations vanish automatically is a fantastic feature.

**Comment by sagebind** [comment]
Regardless of what behavior dropping `HttpClient` has, yes, dropping either a `Response<Body>` or a `ResponseFuture` will make a best-effort to abort the transfer. This behavior does already work, though there's a couple of optimizations we could make still (after dropping `Body`, curl might do 1 more read before aborting). Communication is done via message passing to avoid slowing transfers down with synchronization, so there's always a chance of one more tick of the event loop before the transfer is aborted.

**Comment by sagebind** [comment]
This fix will be included in the next release.
