### ISSUE TITLE
Compilation fails to link static libcurl on macOS <= 10.13

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#68]
See https://github.com/alexcrichton/curl-rust/issues/279.

Statically linking to libcurl is currently broken on macOS <= 10.13 due to a missing symbol.

Generally static linking is preferred unless there's a good reason not to do it, because it means you are running against a consistent, immutable version of the library and have less system dependencies; both of which are great for portability and testability.

We could either wait for this to get fixed upstream and recommend that people disable the `static-curl` feature, or disable it by default, or find another workaround.

There does appear to already be an upstream PR to fix this, so it might be worth waiting it out to see if it is merged and published soon: https://github.com/alexcrichton/curl-rust/pull/283

**Comment by sagebind** [comment]
Good news, this was fixed upstream by https://github.com/alexcrichton/curl-rust/pull/314! Now we just have to force `curl-sys` to version 0.4.25 to get this applied to Isahc.

**Comment by sagebind** [comment]
`curl-sys` version 0.4.26 has now been published, so in theory all we have to do is bump our dependency to `0.4.26` to fix this issue now.

**Comment by sagebind** [comment]
This is now fixed in the [0.9.0](https://github.com/sagebind/isahc/releases/tag/0.9.0) release!

**Comment by NikosEfthias** [comment]
curl requires openssl which makes is impossible to be able to be built out of box for musl targets. Do you think there is anything to do about this ?

**Comment by sagebind** [comment]
I think for musl targets the appropriate solution would be to either disable the `static-curl` feature, or to configure TLS differently, either by using MesaLink with the `curl/mesalink` feature or by attempting to statically compile OpenSSL as well with the `curl/static-ssl` feature. I'm not sure what the best approach would be there.
