### ISSUE TITLE
Expose curl metrics

### ISSUE THREAD

**Issue by EliSnow** [sagebind/isahc#76]
Curl exposes many metrics about requests and responses that would be nice to have. I don't know about curllib but I know through the [CLI](https://curl.haxx.se/docs/manpage.html) these metrics are available through the `--write-out` flag. Specifically I'd be interested in the `size_*`, `time_*` and `speed_*` metrics.

**Comment by sagebind** [comment]
I think this might be a dupe of #47. What do you think?

**Comment by EliSnow** [comment]
I think you're right. I'll watch that one. Thanks, for the quick response
