### ISSUE TITLE
Support for tracing crate

### ISSUE THREAD

**Issue by sagebind** [sagebind/isahc#77]
Add support for the budding [`tracing`](https://github.com/tokio-rs/tracing) framework. Since Isahc is concurrent and can deal with a lot of interleaved requests, it could be very helpful both for Isahc maintainers and for library users to be able to trace individual outgoing requests when something goes wrong. Isahc is also designed to work well as a client in async server applications, which seems to be a target use-case for `tracing`.

Initial experimentation reveals that even in its current state `tracing` should be really easy to integrate. However, the last thing I want to do is leave `log` users out in the cold; indeed, `log` should remain a first-class use case. We will want to make `tracing` optional in some fashion:

- Make the `tracing` dependency optional, and conditionally compile log lines as `log` invocations or `tracing` invocations if it is compiled in. This is a good way to ease into tracing, but might make our use of tracing a little bit limited (unless we have a fancy macro wrapping both).
- Remove `log` dependency and make `tracing` a hard requirement, but with the `tracing/log` feature enabled.

I'd be curious to hear what the `tracing` developers recommend for library authors to do in this situation.

**Comment by yoshuawuyts** [comment]
@sagebind I believe tracing is already capable of capturing `log` messages, so it should already support it. Though it might be that there are a few efficiencies provided by using `tracing` directly.

Regardless of choice, I would like to see `log` to remain a first-class citizen, as crates such as [`async-log`](http://docs.rs/async-log/) provide much of what `tracing` provides for our use already.

**Comment by sagebind** [comment]
Having actually experimented with `tracing` now (previously I was just speculating) it seems like the `tracing/log` feature works in a better way than I was thinking. Depending on just `tracing` with that feature enabled seems to be the best middle ground. `log` users can be totally unaware that `tracing` was involved at all since everything is still forwarded as normal logs unless the application opts-in to a tracing subscriber.

Having a macro that switches between `tracing` and `log` as originally proposed seems like a lot of effort for not much gain, seeing as `tracing` is already a light dependency. Not only do `info!` and friends have to be swapped out, but all uses of `span` and `#[instrument]` also have to be conditional.

Either way, I agree that `log` should remain first class and most libraries probably shouldn't support `tracing` without also supporting `log`.
