### ISSUE TITLE
Streaming response body with cancellation example.

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#87]
Please provide an example on how to stream a response body in a future. How would I cancel it mid-way after a certain number of bytes have been read, or based on inspection of the data so far.

**Comment by sagebind** [comment]
I created a short example program that should help you: https://github.com/sagebind/isahc/blob/f31de5d6f3027c4e95e36c81fc89492c137189bc/examples/stream_cancellation.rs

Feel free to ask if you have more questions!
