### ISSUE TITLE
text() should attempt conversion to UTF-8

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#90]
Either auto-detect content encoding from the response header or accept an encoding as a parameter.

**Comment by sagebind** [comment]
We'll have to pull in encoding crate(s) for this for proper, since the possible content encodings is large. It might be necessary to put this behind a crate feature, since it would be a shame to pull in huge binaries for text decoding for those who don't need it.

**Comment by kathampy** [comment]
Will it also be possible to use `Text<Body>` with `AsyncReadExt` functions like `take(self, limit: u64) -> Take<Self>` so encoding can be applied automatically?

**Comment by sagebind** [comment]
Not now, that would be a breaking API change. Right now it returns `Text<'r>`, which reads the entire response body into memory into a `String`. There's not currently a way of obtaining a `Text<'r>` from an arbitrary `AsyncRead`, which is what `take()` returns (a new `AsyncRead`).

**Comment by sagebind** [comment]
This is now available in the [0.9](https://github.com/sagebind/isahc/releases/tag/0.9.0) release!
